//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cesgranrio.CorretorDeProvas.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeCorrecao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradeCorrecao()
        {
            this.Pontuacao = new HashSet<Pontuacao>();
            this.Questao = new HashSet<Questao>();
        }
    
        public int GradeCorrecaoID { get; set; }
        public decimal GradeCorrecaoFidelidadeAoTema { get; set; }
        public decimal GradeCorrecaoOrganizacaoIdeias { get; set; }
        public decimal GradeCorrecaoNivelDeLinguagem { get; set; }
        public decimal GradeCorrecaoDominioDasRegras { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pontuacao> Pontuacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questao> Questao { get; set; }
    }
}
