//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cesgranrio.CorretorDeProvas.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GradeCorrecao> GradeCorrecao { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Pontuacao> Pontuacao { get; set; }
        public virtual DbSet<Questao> Questao { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<string> Autenticar(string usuarioCPF, string usuarioSenha)
        {
            var usuarioCPFParameter = usuarioCPF != null ?
                new ObjectParameter("UsuarioCPF", usuarioCPF) :
                new ObjectParameter("UsuarioCPF", typeof(string));
    
            var usuarioSenhaParameter = usuarioSenha != null ?
                new ObjectParameter("UsuarioSenha", usuarioSenha) :
                new ObjectParameter("UsuarioSenha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Autenticar", usuarioCPFParameter, usuarioSenhaParameter);
        }
    }
}
