//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cesgranrio.CorretorDeProvas.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questao()
        {
            this.Pontuacao = new HashSet<Pontuacao>();
        }
    
        public int QuestaoID { get; set; }
        public int QuestaoNumero { get; set; }
        public string QuestaoEnunciado { get; set; }
        public int GradeCorrecaoID { get; set; }
    
        public virtual GradeCorrecao GradeCorrecao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pontuacao> Pontuacao { get; set; }
    }
}
