// <auto-generated />
namespace Cesgranrio.CorretorDeProvas.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RespostaControleVersao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RespostaControleVersao));
        
        string IMigrationMetadata.Id
        {
            get { return "201705022333342_RespostaControleVersao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
