// <auto-generated />
namespace Cesgranrio.CorretorDeProvas.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Resposta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resposta));
        
        string IMigrationMetadata.Id
        {
            get { return "201705031848423_Resposta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
